kafka:
  topic:
    hub: telemetry.hubs.v1
    sensor: telemetry.sensors.v1
  bootstrap:
    server: localhost:9092

server:
  port: 8081

grpc:
  server:
    port: 59091

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: false
    hostname: external.host
    metadataMap:
      customParam: customValue
      anotherParam: anotherValue